# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 474)
        MainWindow.setStyleSheet("background-color: rgb(12, 12, 12);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.clear_entry = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.clear_entry.sizePolicy().hasHeightForWidth())
        self.clear_entry.setSizePolicy(sizePolicy)
        self.clear_entry.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.clear_entry.setObjectName("clear_entry")
        self.gridLayout.addWidget(self.clear_entry, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(
            'font: 75 28pt "MS Shell Dlg 2";\n' "color: rgb(255, 255, 255);"
        )
        self.label.setText("")
        self.label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.three = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.three.sizePolicy().hasHeightForWidth())
        self.three.setSizePolicy(sizePolicy)
        self.three.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 3, 2, 1, 1)
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.minus.sizePolicy().hasHeightForWidth())
        self.minus.setSizePolicy(sizePolicy)
        self.minus.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 3, 3, 1, 1)
        self.decimal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.decimal.sizePolicy().hasHeightForWidth())
        self.decimal.setSizePolicy(sizePolicy)
        self.decimal.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.decimal.setObjectName("decimal")
        self.gridLayout.addWidget(self.decimal, 4, 2, 1, 1)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 4, 3, 1, 1)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 5, 2, 1, 2)
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.zero.sizePolicy().hasHeightForWidth())
        self.zero.setSizePolicy(sizePolicy)
        self.zero.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 4, 1, 1, 1)
        self.six = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.six.sizePolicy().hasHeightForWidth())
        self.six.setSizePolicy(sizePolicy)
        self.six.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 2, 2, 1, 1)
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.multiply.sizePolicy().hasHeightForWidth())
        self.multiply.setSizePolicy(sizePolicy)
        self.multiply.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.multiply.setObjectName("multiply")
        self.gridLayout.addWidget(self.multiply, 2, 3, 1, 1)
        self.two = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.two.sizePolicy().hasHeightForWidth())
        self.two.setSizePolicy(sizePolicy)
        self.two.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 3, 1, 1, 1)
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.seven.sizePolicy().hasHeightForWidth())
        self.seven.setSizePolicy(sizePolicy)
        self.seven.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 1, 0, 1, 1)
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.equal.sizePolicy().hasHeightForWidth())
        self.equal.setSizePolicy(sizePolicy)
        self.equal.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 4, 0, 1, 1)
        self.four = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.four.sizePolicy().hasHeightForWidth())
        self.four.setSizePolicy(sizePolicy)
        self.four.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 2, 0, 1, 1)
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.eight.sizePolicy().hasHeightForWidth())
        self.eight.setSizePolicy(sizePolicy)
        self.eight.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 1, 1, 1, 1)
        self.one = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.one.sizePolicy().hasHeightForWidth())
        self.one.setSizePolicy(sizePolicy)
        self.one.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 3, 0, 1, 1)
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.divide.sizePolicy().hasHeightForWidth())
        self.divide.setSizePolicy(sizePolicy)
        self.divide.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 1, 3, 1, 1)
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.nine.sizePolicy().hasHeightForWidth())
        self.nine.setSizePolicy(sizePolicy)
        self.nine.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 1, 2, 1, 1)
        self.five = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.five.sizePolicy().hasHeightForWidth())
        self.five.setSizePolicy(sizePolicy)
        self.five.setStyleSheet(
            "QPushButton{\n"
            'font: 75 20pt "MS Shell Dlg 2";\n'
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(191, 191, 191);\n"
            "border-radius:30px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgb(61, 61, 61);\n"
            "    background-color: rgb(238, 238, 238);\n"
            "}\n"
            "\n"
            "QPushBotton{\n"
            "background-color: rgb(208, 0, 0);\n"
            "    color: rgb(255, 255, 255);\n"
            "}"
        )
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.one.clicked.connect(self.method_1)
        self.two.clicked.connect(self.method_2)
        self.three.clicked.connect(self.method_3)
        self.four.clicked.connect(self.method_4)
        self.five.clicked.connect(self.method_5)
        self.six.clicked.connect(self.method_6)
        self.seven.clicked.connect(self.method_7)
        self.eight.clicked.connect(self.method_8)
        self.nine.clicked.connect(self.method_9)
        self.zero.clicked.connect(self.method_zero)
        self.equal.clicked.connect(self.method_equal)
        self.decimal.clicked.connect(self.method_point)
        self.add.clicked.connect(self.method_plus)
        self.minus.clicked.connect(self.method_min)
        self.multiply.clicked.connect(self.method_mult)
        self.divide.clicked.connect(self.method_div)
        self.clear.clicked.connect(self.method_clear)
        self.clear_entry.clicked.connect(self.method_ce)

    def method_1(self):
        text = self.label.text()
        self.label.setText(text + "1")

    def method_2(self):
        text = self.label.text()
        self.label.setText(text + "2")

    def method_3(self):
        text = self.label.text()
        self.label.setText(text + "3")

    def method_4(self):
        text = self.label.text()
        self.label.setText(text + "4")

    def method_5(self):
        text = self.label.text()
        self.label.setText(text + "5")

    def method_6(self):
        text = self.label.text()
        self.label.setText(text + "6")

    def method_7(self):
        text = self.label.text()
        self.label.setText(text + "7")

    def method_8(self):
        text = self.label.text()
        self.label.setText(text + "8")

    def method_9(self):
        text = self.label.text()
        self.label.setText(text + "9")

    def method_zero(self):
        text = self.label.text()
        self.label.setText(text + "0")

    def method_point(self):
        text = self.label.text()
        self.label.setText(text + ".")

    def method_plus(self):
        text = self.label.text()
        self.label.setText(text + "+")

    def method_min(self):
        text = self.label.text()
        self.label.setText(text + "-")

    def method_mult(self):
        text = self.label.text()
        self.label.setText(text + "*")

    def method_div(self):
        text = self.label.text()
        self.label.setText(text + "/")

    def method_clear(self):
        self.label.setText("")

    def method_ce(self):
        text = self.label.text()
        self.label.setText(text[: len(text) - 1])

    def method_equal(self):
        text = self.label.text()

        try:
            ans = eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.clear_entry.setText(_translate("MainWindow", "CE"))
        self.three.setText(_translate("MainWindow", "3"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.decimal.setText(_translate("MainWindow", "."))
        self.add.setText(_translate("MainWindow", "+"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.six.setText(_translate("MainWindow", "6"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.two.setText(_translate("MainWindow", "2"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.equal.setText(_translate("MainWindow", "="))
        self.four.setText(_translate("MainWindow", "4"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.one.setText(_translate("MainWindow", "1"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.five.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
